[package]
name = "pixels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
inputbot = "0.6.0"
screenshots = "0.8.5"
termion = "2.0.1"
whoami = "1.4.1"
